{% set name = "sphinx-book-theme" %}
{% set version = "0.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f358e1de7564499a61f4061315386ac8a35e4ba4076974de6dffc9f934d9c00a
  - folder: src
    url: https://github.com/executablebooks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e19b72c74c1af29f629a903c15f102c3ae1e15ff7c75fe30fbd400e5788b4152

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - click >=7.1,<8
    - docutils >=0.15,<0.17
    - pydata-sphinx-theme >=0.7.2,<0.8
    - python >=3.7
    - pyyaml
    - sphinx >=3,<5

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov sphinx_book_theme --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - myst-nb
    - pip
    - pytest-cov
    - pytest-regressions
    - sphinx-thebe

about:
  home: https://sphinx-book-theme.readthedocs.org
  summary: 'A clean book theme for scientific explanations and documentation with Sphinx'
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
