{% set name = "sphinx-book-theme" %}
{% set version = "0.1.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 42d3b166889f675074f2471de0a7ce4016f9a14e7ec2ab0c924c627f8de2d24b
  - folder: src
    url: https://github.com/executablebooks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e08c3647dd57f7add5864bd82cff5baba709d94b91c9c8ab0a2f92f32a9457ea

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - click >=7.1,<8
    - docutils >=0.15,<0.17
    - importlib_resources >=3.0,<3.5
    - pydata-sphinx-theme >=0.7.2,<0.8
    - python >=3.7
    - pyyaml
    - sphinx >=3,<5

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov sphinx_book_theme --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - myst-nb
    - pip
    - pytest-cov
    - pytest-regressions
    - sphinx-thebe

about:
  home: https://jupyterbook.org
  summary: 'Jupyter Book: Create an online book with Jupyter Notebooks'
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: dist/LICENSE
  doc_url: https://sphinx-book-theme.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
