{% set name = "sphinx-book-theme" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2fa4320264f4e365959f6a1370df7f76922781f0cc755a9e0974b1b17fa99888
  - folder: src
    url: https://github.com/executablebooks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3c006473a6bb127c592b836b0b02e7c2863bc3e2b2b7f31b4b5d542a07680919

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - click
    - docutils >=0.15
    - importlib_resources >=3.0,<3.5
    - pydata-sphinx-theme >=0.6.0,<0.7
    - python >=3.7
    - pyyaml
    - sphinx >=2,<4

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov sphinx_book_theme --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - myst-nb
    - pip
    - pytest-cov
    - pytest-regressions
    - sphinx-thebe
    # fixed upstream in pydata-sphinx-theme and jupyter-cache, but still brings in builds which didn't specify these pins
    # - docutils <0.17
    # - sqlalchemy >=1.3.12,<1.4

about:
  home: https://jupyterbook.org
  summary: 'Jupyter Book: Create an online book with Jupyter Notebooks'
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: dist/LICENSE
  doc_url: https://sphinx-book-theme.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
