{% set version = "0.2.0" %}

package:
  name: sphinx-book-theme
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/s/sphinx-book-theme/sphinx-book-theme-{{ version }}.tar.gz
    sha256: 9f9762f2c6372e7ebaac905707628efe80386d3e5160945d8965d309aeed940d
  - folder: src
    url: https://github.com/executablebooks/sphinx-book-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3d5521acf01a22895a40e09ac4b77410191ad8912b26f2215a7a0e9600849e84

build:
  number: 1
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - docutils >=0.15,<0.17
    - pydata-sphinx-theme >=0.7.2,<0.8
    - python >=3.7
    - pyyaml
    - sphinx >=3,<5

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov sphinx_book_theme --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - myst-nb
    - pip
    - pytest-cov
    - pytest-regressions
    - sphinx-thebe

about:
  home: https://sphinx-book-theme.readthedocs.org
  summary: A clean book theme for scientific explanations and documentation with Sphinx
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
