{% set name = "sphinx-book-theme" %}
{% set version = "0.0.38" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-book-theme-{{ version }}.tar.gz
  sha256: e64350754ce505f3aad101d79aad8089111b3797f2cb492d0cace01069579d36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - click
    - docutils >=0.15
    - pydata-sphinx-theme >=0.4.1,<0.5.0
    - python >=3.7
    - pyyaml
    - sphinx

test:
  imports:
    - sphinx_book_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jupyterbook.org/
  summary: 'Jupyter Book: Create an online book with Jupyter Notebooks'
  dev_url: https://github.com/jupyter/jupyter-book/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
