{% set name = "sphinx-book-theme" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a9aa7e7e6eff879b998677a184d11a5835b6552732e7404776a2dfed942671f9
  - folder: src
    url: https://github.com/executablebooks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e06d6193b3d381e50be4a3614a0e5193f30cfc184534ed1d105098dd2a2a5613

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - click >=7.1,<8
    - docutils >=0.15,<0.17
    - importlib_resources >=3.0,<3.5
    - pydata-sphinx-theme >=0.6.0,<0.7re
    - python >=3.7
    - pyyaml
    - sphinx >=3,<5

test:
  source_files:
    - src/tests
  imports:
    - sphinx_book_theme
  commands:
    - pip check
    - cd src
    - pytest -vv --cov sphinx_book_theme --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - myst-nb
    - pip
    - pytest-cov
    - pytest-regressions
    - sphinx-thebe

about:
  home: https://jupyterbook.org
  summary: 'Jupyter Book: Create an online book with Jupyter Notebooks'
  dev_url: https://github.com/executablebooks/sphinx-book-theme
  license: BSD-3-Clause
  license_file: dist/LICENSE
  doc_url: https://sphinx-book-theme.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
